name: Go Test

on:
  push:
    branches:
      - main  # mainブランチへのプッシュをトリガーにする

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          go mod tidy  # 依存関係を整える
        working-directory: ./srcs/

      - name: Run tests
        run: |
          go test -v ./...  # すべてのテストを実行
        working-directory: ./srcs/
